config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts, only: [:show, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :posts, except: [:show, :index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/post.rb
class Post < ApplicationRecord
  
  mount_uploader :image, ImageUploader
  validates :title, :summary, :body, presence: true  # проверка на непустое значение

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :danger, :info, :warning
end

app/controllers/concerns/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  layout "admin"

  protected

  def check_admin
    redirect_to root_path, alert: "У вас нет прав доступа" unless current_user.admin?
  end
end

app/controllers/concerns/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController

  before_action :set_post, only:[ :edit, :update, :destroy ]


  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
     redirect_to @post, success: 'Статья успешно создана'
    else
      render :new, danger: 'Статья не создана'
    end
  end

  def edit
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to @post, success: 'Статья успешно обновлена'
    else
      render :edit, danger: 'Статья не обновлена'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, success: 'Статья успешно удалена'
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :summary, :body, :image)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: :show

  def index
    @posts = Post.paginate(page: params[:page], per_page: 5)
  end


  def show
    @random_posts = Post.limit(2).order("RANDOM()")
  end


  private

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(name)
    { success: "alert-success",
      error: "alert-danger",
      danger: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }[name.to_sym] || name
  end
end

app/views/admin/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [:admin, @post], html: { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
    <%= link_to 'Назад', :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Редактирование статьи</h1>

<%= render 'form'%>

app/views/admin/posts/new.html.erb
<h1>Новая статья</h1>

<%= render 'form'%>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <nav class="navbar navbar-toggleable-mb navbar-inverse bg-inverse" style="background-color: grey;>
        <a class="navbar-brand" href="#">Админпанель</a>
        <div class="nav">
          <a class="nav-link active" href="<%= posts_path %>">Все статьи</a>
        </div>

        <ul class="navbar-nav pull-xs-right">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Выход", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Вход", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Регистрация", new_user_registration_path, class: "nav-link" %>
          </li>
          <% end %>
        </ul>
      </nav>
    </div>

    <div class="container main">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert <%= bootstrap_class_for(name) %>">
              <button class="close" data-dismiss="alert">&times;</button>
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>

    <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <nav class="navbar navbar-light bg-faded" style="background-color: #e3f2fd;" >
        <div class="nav">
          <a class="nav-link active" href="<%= posts_path %>">Все статьи</a>
        </div>
        <%= link_to 'Новая статья', new_post_path, class:'btn btn-outline-primary pull-xs-right' %>
        <ul class="navbar-nav pull-xs-right">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Выход", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Вход", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Регистрация", new_user_registration_path, class: "nav-link" %>
          </li>
          <% end %>
        </ul>
      </nav>
    </div>

    <div class="container main">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert <%= bootstrap_class_for(name) %>">
              <button class="close" data-dismiss="alert">&times;</button>
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>

    <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application0.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <nav class="navbar navbar-light bg-faded" style="background-color: #e3f2fd;" >
        <div class="nav">
          <a class="nav-link active" href="<%= posts_path %>">Все статьи</a>
        </div>
        
        <ul class="navbar-nav pull-xs-right">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Выход", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Вход", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Регистрация", new_user_registration_path, class: "nav-link" %>
          </li>
          <% end %>
        </ul>
      </nav>
    </div>

    <div class="container main">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert <%= bootstrap_class_for(name) %>">
              <button class="close" data-dismiss="alert">&times;</button>
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>

    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post, html: { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
    <%= link_to 'Назад', :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <small>
      <time><%= post.created_at.to_date.strftime("%d %B, %Y") %></time>
      |
      <% if user_signed_in? && current_user.admin? %>
        <%= link_to "Изменить", edit_admin_post_path(post) %>
        |
        <%= link_to "Удалить", admin_post_path(post), method: :delete, data: { confirm: 'Удалить статью?'} %>
      <% end %>
    </small>


  </section>

  <section class="post-summary clearfix">
    <%= image_tag post.image.url(:thumb), class: 'img-thumbnail thumb' if post.image? %>
    <%= post.summary %>
  </section>
</article>

app/views/posts/index.html.erb
<h1>Статьи<h1>

<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'Новая статья', new_admin_post_path, class:'btn btn-outline-primary btn-sm' %>
<% end %>

<%= render @posts %>

<nav aria-label="Page navigation example">
  <ul class="pagination pagination-sm justify-content-center">
    <li class="page-item"><a class="page-link" href="/?page=1">1</a></li>
    <li class="page-item"><a class="page-link" href="/?page=2">2</a></li>
  </ul>
</nav>

app/views/posts/show.html.erb
<article class="post">
  <section class="post-head">
    <h1><%= @post.title %></h1>
    <small>
      <time><%= @post.created_at.to_date.strftime("%d %B, %Y") %></time>
      |
      <% if user_signed_in? && current_user.admin? %>
        <%= link_to "Изменить", edit_admin_post_path(@post) %>
        |
        <%= link_to "Удалить", admin_post_path(@post), method: :delete, data: { confirm: 'Удалить статью?'} %>
      <% end %>
    </small>
  </section>

  <section class="post-body">
    <%= image_tag @post.image.url(:large), class: 'img-show' if @post.image? %>
    <%= @post.body %>
  </section>

  <p><%= @random_posts %></p>

</article>